version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable
    container_name: poc-nginx
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: poc-mysql
    restart: unless-stopped
    ports:
      - ${DB_PORT_LOCAL:-33060}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  mysql_testing:
    image: mysql:5.7
    container_name: poc-mysql-testing
    tmpfs: /var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}_testing
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  php:
    image: thomasowow/laravel-php:7.4
    container_name: poc-php
    tty: true
    volumes:
      - .:/var/www/html:cached
      - ./docker/php.ini:/usr/local/etc/php/conf.d/99-docker.ini
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: poc-pma
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - ${DB_PORT_LOCAL:-8080}:80
    networks:
      - laravel

  ngrok:
    image: wernight/ngrok
    container_name: poc-ngrok
    ports:
      - "4040:4040"
    depends_on:
      - nginx
    environment:
      - NGROK_AUTH=1hdMztixxxvkg1107eUtzdzX3Yh_3zBooANGp3oYTriSmC9YP
      - NGROK_REGION=eu
      - NGROK_PORT=nginx:80
    networks:
      - laravel
